/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SaxDac.h"
#include "sax_isr.h"
#include "Audio_Out1_aliases.h"
#include "Audio_Out1.h"
#include "sax_clk.h"
#include "LCD_Char_1.h"
#include "lcd_isr.h"
#include "Clock_1.h"
#include "led_aliases.h"
#include "led.h"
#include "led1_aliases.h"
#include "led1.h"
#include "testy_aliases.h"
#include "testy.h"
#include "PianoDac.h"
#include "piano_clk.h"
#include "piano_isr.h"
#include "Pot_1_aliases.h"
#include "Pot_1.h"
#include "BPM_ADC.h"
#include "PITCH_ADC.h"
#include "POT_2_aliases.h"
#include "POT_2.h"
#include "Audio_Out2_aliases.h"
#include "Audio_Out2.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "BPM_ADC_AMux.h"
#include "BPM_ADC_Ext_CP_Clk.h"
#include "BPM_ADC_IRQ.h"
#include "BPM_ADC_theACLK.h"
#include "PITCH_ADC_IRQ.h"
#include "PITCH_ADC_theACLK.h"
#include "PITCH_ADC_Bypass_aliases.h"
#include "PITCH_ADC_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

